#!/usr/bin/env python 
import os
import sys
from coffea import util, hist
import re
from copy import deepcopy
import psutil
process = psutil.Process(os.getpid())

if __name__ == "__main__":
  import argparse
  parser = argparse.ArgumentParser(description="Add coffea subjobs back together")
  parser.add_argument("output_file", type=str, help="Output path")
  parser.add_argument("input_files", type=str, nargs="+", help="Input files")
  parser.add_argument("-f", "--force", action="store_true", help="Force overwrite")
  args = parser.parse_args()

  print(f"[cadd] Output file = {args.output_file}")

  output = None
  for i, input_file in enumerate(args.input_files):
    print(f"[cadd] \tInput file {i}/{len(args.input_files)} => {input_file}")
    this_input = util.load(input_file)
    if not output:
      output = deepcopy(this_input)
    else:
      #assert set(output.keys()) == set(this_input.keys())
      #print(output)
      output.add(this_input)
    del this_input
    #print("Done with this file. mem={}".format(print(process.memory_info().rss)))
  #print("Trying to save now. mem={}".format(print(process.memory_info().rss)))
  util.save(output, args.output_file)
